DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS weather;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE weather (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cit_1 TEXT NOT NULL,
  cit_2 TEXT NOT NULL,
  cit_3 TEXT NOT NULL,
  cit_4 TEXT NOT NULL,
  cit_5 TEXT NOT NULL,
  temp_1 FLOAT NOT NULL,
  temp_2 FLOAT NOT NULL,
  temp_3 FLOAT NOT NULL,
  temp_4 FLOAT NOT NULL,
  temp_5 FLOAT NOT NULL,
  f_l_1 FLOAT NOT NULL,
  f_l_2 FLOAT NOT NULL,
  f_l_3 FLOAT NOT NULL,
  f_l_4 FLOAT NOT NULL,
  f_l_5 FLOAT NOT NULL,
  con_1 TEXT NOT NULL,
  con_2 TEXT NOT NULL,
  con_3 TEXT NOT NULL,
  con_4 TEXT NOT NULL,
  con_5 TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
